### ISSUE TITLE
Discord pipe socket doesn't start correctly

### ISSUE THREAD

**Issue by Pepijn98** [BRForgers/RichPresence-Addon#1]
Trying to start dps using `java -jar ./dps-fat-1.0.jar` but it throws an exception.

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.awt.TrayIcon.<init>(TrayIcon.java:144)
	at java.awt.TrayIcon.<init>(TrayIcon.java:168)
	at br.com.brforgers.armelin.dps.DiscordPipeSocket.main(DiscordPipeSocket.java:91)
```

**Comment by allanf181** [comment]
OS?

**Comment by Pepijn98** [comment]
Ubuntu 18.04

**Comment by allanf181** [comment]
https://stackoverflow.com/questions/50440268/the-system-tray-is-not-supported-on-the-current-platform

**Comment by Pepijn98** [comment]
Okay thanks that's 1 step closer to it working, it starts but when I enable the addon it throws another exception

```
Uncaught exception in thread "WebSocketWorker-10":java.lang.ExceptionInInitializerError
	at br.com.brforgers.armelin.dps.DiscordPipeSocket$1.onMessage(DiscordPipeSocket.java:52)
	at org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:569)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:906)
Caused by: java.lang.NullPointerException
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2314)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2270)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:2291)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:2246)
	at net.arikia.dev.drpc.DiscordRPC.loadDLL(DiscordRPC.java:150)
	at net.arikia.dev.drpc.DiscordRPC.<clinit>(DiscordRPC.java:22)
	... 6 more
```

**Comment by allanf181** [comment]
The lib used in dps is not compatible with Linux-based systems, I can try to compile with a compatible lib but it may take time.

**Comment by Pepijn98** [comment]
Ah okay, thanks for the fast replies, it would be great if you could compile it with a compatible lib.

**Comment by allanf181** [comment]
try this
https://cdn.discordapp.com/attachments/326902255401959424/556257554754175018/dps-fat-1.0.jar

**Comment by Pepijn98** [comment]
Yep it works perfectly, thanks for the quick update!
